/**
 * The event vocabulary this build understands, and the three standings one
 * event can have against it.
 *
 * The set is a build-time constant of `@deepseek-ai/dsh-session`
 * (`packages/core/session/src/known-event-types.ts`, generated by
 * `scripts/gen-persistence-catalog.ts`). Because it is generated from the
 * event types declared *in this repository*, an out-of-repo plugin's type is
 * outside it by construction — the module's own doc comment says so, and says
 * the compatibility mechanism is the persisted envelope marker rather than
 * event-name registration.
 *
 * This module resolves that set through the peer dependency, so within one
 * process it is the host's copy. {@link vocabularyReport} records which build
 * answered, because a plugin that carries its own copy of `dsh-session` would
 * otherwise silently classify against a vocabulary the host does not use.
 *
 * @module @argszero/cordis-plugin-session-event-guard/vocabulary
 */

import { createRequire } from 'node:module'
import { KNOWN_SESSION_EVENT_TYPES } from '@deepseek-ai/dsh-session'

/**
 * How one event stands against a reader's vocabulary.
 *
 * - `known`: the type is in this build's generator output, so every build of
 *   this line interprets it.
 * - `omittable`: unknown, but the envelope carries `ignorable: true`. A
 *   conforming reader may skip it and reconstruct the rest of the session.
 * - `required`: unknown and unmarked. A conforming reader MUST refuse the
 *   whole log rather than silently drop an event it cannot interpret, because
 *   an unrecognized required event may change how the rest of the log reads.
 */
export type EventStanding = 'known' | 'omittable' | 'required'

/** The vocabulary this process's `dsh-session` declares. */
export const KNOWN_EVENT_TYPES: ReadonlySet<string> = KNOWN_SESSION_EVENT_TYPES

/**
 * The standing of one type name against this build's vocabulary.
 * @param type - the event type name as it would be stored.
 * @param ignorable - the envelope's marker, when the envelope being judged has one.
 * @returns the standing.
 */
export function standingOf(type: string, ignorable?: unknown): EventStanding {
  if (KNOWN_EVENT_TYPES.has(type)) return 'known'
  return ignorable === true ? 'omittable' : 'required'
}

/** Which build answered the vocabulary question, for disclosure in a report. */
export interface VocabularyReport {
  /** Number of event types the resolved build declares. */
  size: number
  /** Version of the resolved `@deepseek-ai/dsh-session`, or `unknown`. */
  version: string
}

/**
 * Identify the `dsh-session` build whose vocabulary {@link KNOWN_EVENT_TYPES}
 * is. Disclosed rather than assumed: a plugin loaded with its own nested copy
 * would classify against a different set than the host's read path, and the
 * only honest thing to do is name the build that answered.
 * @returns the size and resolved version.
 */
export function vocabularyReport(): VocabularyReport {
  return { size: KNOWN_EVENT_TYPES.size, version: resolvedSessionVersion() }
}

/**
 * Read the version of the resolved peer, without importing runtime code from
 * it a second time.
 * @returns the version string, or `unknown` when the manifest is unreachable.
 */
function resolvedSessionVersion(): string {
  try {
    const require = createRequire(import.meta.url)
    const manifest: unknown = require('@deepseek-ai/dsh-session/package.json')
    const version = (manifest as { version?: unknown }).version
    return typeof version === 'string' ? version : 'unknown'
  } catch {
    return 'unknown'
  }
}
